### ISSUE TITLE
Activation in RRN

### ISSUE THREAD

**Issue by dennisc1** [AndreaCossu/Relation-Network-PyTorch#2]
Hi Andrea,
Thanks for this neat implementation! 

I've noticed the MLP consists of linear layers followed by a tanh layer ([code](https://github.com/AndreaCossu/Relation-Network-PyTorch/blob/5ecb8148b73b618ff33b03420c4af25f2566811f/src/models/MLP.py#L35-L36)). However, in the RRN paper the authors mention using ReLu layers followed by a linear layer. Is this variation intentional?

**Comment by AndreaCossu** [comment]
Hello Dennis,

I hardcoded the activation function as tanh just to experiment with it but my final aim is to make the activation function a parameter in the constructor of the MLP. As soon as I have time I will make this change.

**Comment by dennisc1** [comment]
Ok great, just checking if there was any other reason.
